config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "admin/index"

  root to: "home#index"
  get "/.well-known/acme-challenge/:id" => "home#letsencrypt"
  get "/all_locations", to: "locations#all_locations"
  get "/connect_groups/approve", to: "connect_groups#not_approved_index"
  get "/register", to: "connect_groups#new"
  get "/events/revelstoke", to: "events#revelstoke"
  get "/events/kelowna", to: "events#kelowna"
  get "new", to: "home#new"
  resources :connect_groups, :podcasts, :event_types, :events, :messages
  resources :contributions, only: [:new, :create, :index]

  mount Shrine.presign_endpoint(:cache) => "/presign"

  get "app_giving", to: "contributions#new_app"
  get "admin", to: "home#admin"
  get "believe", to: "home#believe"
  get "connect", to: "connect_groups#index"
  get "connection", to: "home#connection"
  get "expect", to: "home#expect"
  get "give", to: "contributions#new"
  get "kids", to: "home#kids"
  get "media", to: "home#media"
  get "nextstep", to: "home#nextstep"
  get "pastors", to: "home#pastors"
  get "vernon", to: "home#vernon"
  get "team", to: "home#pastors"
  get "verse_of_the_day", to: "home#verse_of_the_day"
  get "/team", to: redirect("/pastors")
  get "/vision", to: redirect("believe")
  get "/giving", to: redirect("give")
  get "/feeds/revelstoke", to: "podcasts#revelstoke", defaults: {format: "xml"}
  get "/feeds/kelowna", to: "podcasts#kelowna", defaults: {format: "xml"}
  get "/admin/events", to: "events#admin"

  get "/ajax_load_dashboard", to: "home#ajax_load_dashboard"
  get "/ajax_load_events", to: "home#ajax_load_events"
  get "/ajax_load_locations", to: "home#ajax_load_locations"
  get "/ajax_load_podcasts", to: "home#ajax_load_podcasts"
  get "/ajax_load_connect_groups", to: "home#ajax_load_connect_groups"
  get "/ajax_load_users", to: "home#ajax_load_users"

  #landing page routes go here

  ############################

  match "/loaderio-0077704941f2bf1a629295ce9fb1a229", :to => proc { |env| [200, {}, ["loaderio-0077704941f2bf1a629295ce9fb1a229"]] }, via: :get
  post "podcasts/upload", to: "audio_clips#create"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :locations, only: [:index, :new, :create]
  resources :locations, except: [:index, :new, :create], path: ""

  ### Routing for the new API ###
  namespace :api do
    namespace :v1 do
      resources :locations
      resources :podcasts
      resources :events
      resources :connect_groups
      get "/location/*id", to: "locations#get_location"
      get "/event/featured", to: "events#featured_events"
      get "/homedata", to: "home#index"
    end
  end
end

app/models/home.rb
class Home < ApplicationRecord

	def self.which_sunday(week)
		@week = week - 1
		@today = Date.today
		@current_year = Date.today.year.to_i
		sunday_array(Date.today.month.to_i)
		if Date.new(@current_year, @current_month, @sundays[@week]) <= Time.now.in_time_zone('America/Los_Angeles').to_date
			new_month = Date.today.month.to_i + 1
			new_month == 13 ? new_month = 1 : new_month
			sunday_array(new_month)
		end
		Date.new(@current_year, @current_month, @sundays[@week])
	end
	def self.sunday_array(month)
		@current_month = month
		@days_in_month = Time.days_in_month(@current_month)
		@sundays = Array.new
		@first_sunday = (1..7).find {|d| Date.new(@current_year, @current_month, d).sunday?}
		(@first_sunday...@days_in_month).step(7) {|d| @sundays.push(d).to_ary}
	end
end

app/controllers/api/v1/home_controller.rb
class Api::V1::HomeController < ApiController

  def index
    @featured = Event.all.where(featured: true).order("starttime ASC").as_json(:methods => [:image_url])
    @locations = Location.all.where(show_in_listing: true).as_json(:methods => [:photo_url, :photo_mobile_url, :logo_url])
    render json: { :locations => @locations, :featured => @featured }.to_json
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:admin]
  #  layout :none, only: :verse_of_the_day
  layout "admin", only: :admin
  layout "react", only: :vernon

  def admin
  end

  def index
    @featured = Event.all.where(["starttime > ?", Time.now.ago(2.days)]).order("starttime ASC").where(featured: true).limit(1)
    @listings = Location.all.where(show_in_listing: true)
  end

  def media
    @podcasts = Podcast.all.order("dateof DESC").limit(9)
  end

  def new
    @listings = Location.all.where(show_in_listing: true)
  end

  def expect
    @listings = Location.all.where(show_in_listing: true)
  end

  def nextstep
    @dates = Array.new
    (1..4).each { |d| @dates.push(Home.which_sunday(d)) }
  end

  def vernon
  end

  def letsencrypt
    # use your code here, not mine
    render text: "7fZlPb-fcMhTCqM0v6LKcL5vDJAC79gobZZRZxrSL0c.LUGLpVtUqTXmeOKVq5VWVEEWXPmun8mjkOOfB_gShBE"
  end

  def ajax_load_dashboard
    respond_to do |format|
      format.js
    end
  end

  def ajax_load_events
    respond_to do |format|
      format.js
    end
  end

  def ajax_load_locations
    respond_to do |format|
      format.js
    end
  end

  def ajax_load_podcasts
    respond_to do |format|
      format.js
    end
  end

  def ajax_load_connect_groups
    @connect_groups_not_approved = ConnectGroup.all.where(approved: [nil, false])
    respond_to do |format|
      format.js
    end
  end

  def ajax_load_users
    respond_to do |format|
      format.js
    end
  end
end

app/views/home/admin/_connect_groups.html.erb
<%  if can?(:manage, ConnectGroup)%>
<%= content_tag :div, class: 'row dashboard' do %>
<i class='fa fa-3x fa-cogs'></i><span>Connect Groups</span>
<ul>
  <li><%= link_to(content_tag(:i, " New", class: 'fa fa-plus'), new_connect_group_path) %></li>
   <li class='pending'><%= content_tag(:i, " #{ConnectGroup.approval_pending('Revelstoke')} Pending Approval", class: 'fa fa-check-square-o') %>
</li>
<%= render 'connect_groups/not_approved_list' %>
  <li><%= link_to(content_tag(:i, " List", class: 'fa fa-list'), connect_groups_path) %></li>
</ul>
<% end end %>

app/views/home/admin/_dashboard_campus.html.erb
<section class='stat-dashboard'>
  <div class='bottom-row five'>
    <div class='title'>
      Past Week Totals
      <% if current_user.has_role?( :admin)%>
      <i class='fa fa-refresh' data-ng-click = "refreshData()" title='refresh data'></i>
      <% end %>
    </div>
    <div class='stat <%= trend_stat("Church",:attendance,'sunday') %>'>
      <div class='circle circle-border'>
        <div class='circle-inner'>
          <div class='radial-1 ring-1-63'>
            <div class='radial-2 ring-2-37'>
              <div class='overlay'>
          <div class='stat-text'>
            <%= stat("Church",:attendance,'sunday') %>
          </div>
        </div>
        </div>
        </div>
        </div>
      </div>
      <div class='caption'>Attendance</div>
      <div class="previous">
        <%= stat("Church", :attendance,'last sunday') %>
        <span><%=difference_stat("Church",:attendance,'sunday') %></span>
      </div>
    </div>
    <div class='stat <%= trend_stat("Church",:visitors,'sunday') %>'>
      <div class='circle circle-border'>
        <div class='circle-inner'>
          <div class='stat-text'>
            <%= stat("Church",:visitors,'sunday') %>
          </div>
        </div>
      </div>
      <div class='caption'>Visitors</div>
      <div class="previous">
        <%= stat("Church",:visitors,'last sunday') %>
        <span><%= difference_stat("Church",:visitors,'sunday') %></span>
      </div>
    </div>
    <div class='stat <%= trend_stat("Church",:decisions,'sunday') %>'>
      <div class='circle circle-border'>
        <div class='circle-inner'>
          <div class='stat-text'>
            <%= stat("Church",:decisions,'sunday') %>
          </div>
        </div>
      </div>
      <div class='caption'>Decisions</div>
      <div class="previous">
        <%= stat("Church",:decisions,'last sunday') %>
        <span><%= difference_stat("Church",:decisions,'sunday') %></span>
      </div>
    </div>
    <!--    <div class='stat'>
    <div class='circle circle-border normal'>
    <div class='circle-inner'>
    <div class='stat-text'>
    0
  </div>
</div>
</div>
C3 Team
</div> -->
<div class='stat <%= trend_stat("Next Steps",:attendance,'sunday') %>'>
  <div class='circle circle-border'>
    <div class='circle-inner'>
      <div class='stat-text'>
        <%= stat("Next Steps",:attendance,'sunday') %>
      </div>
    </div>
  </div>
  <div class='caption'>NextSteps</div>
  <div class="previous">
    <%= stat("Next Steps",:attendance,'last sunday') %>
    <span><%= difference_stat("Next Steps",:attendance,'sunday')%></span>
  </div>
</div>
<div class='stat <%= trend_giving("week") %>'>
  <div class='circle circle-border'>
    <div class='circle-inner'>
      <div class='stat-text giving'>
        $<%= giving('week') %>
      </div>
    </div>
  </div>
  <div class='caption'>Giving</div>
  <div class="previous">
    $<%= giving('last week') %>
    <span><%=difference_giving('week')%></span>
  </div>
</div>
</div>
<div class='bottom-row five'>
  <div class='half-page five'>
    <div class='title'>
      Monthly Averages
    </div>
    <div class='stat <%= trend_stat("Church",:attendance,'month') %>'>
      <div class='circle circle-border'>
        <div class='circle-inner'>
          <div class='stat-text'>
            <%= stat("Church",:attendance,'month') %>
          </div>
        </div>
      </div>
      <div class='caption'>Attendance</div>
      <div class="previous">
        <%= stat("Church",:attendance,'last month') %>
        <span><%=difference_stat("Church",:attendance,'month')%></span>
      </div>
    </div>
    <div class='stat <%= trend_stat("Church",:visitors,'month') %>'>
      <div class='circle circle-border'>
        <div class='circle-inner'>
          <div class='stat-text'>
            <%= stat("Church",:visitors,'month') %>
          </div>
        </div>
      </div>
      <div class='caption'>Visitors</div>
      <div class="previous">
        <%= stat("Church",:visitors,'last month') %>
        <span><%=difference_stat("Church",:visitors,'month')%></span>
      </div>
    </div>
    <div class='stat <%= trend_stat("Church",:decisions,'month') %>'>
      <div class='circle circle-border'>
        <div class='circle-inner'>
          <div class='stat-text'>
            <%= stat("Church",:decisions,'month') %>
          </div>
        </div>
      </div>
      <div class='caption'>Decisions</div>
      <div class="previous">
        <%= stat("Church",:decisions,'last month') %>
        <span><%=difference_stat("Church",:decisions,'month')%></span>
      </div>
    </div>
    <!--      <div class='stat'>
    <div class='circle circle-border normal'>
    <div class='circle-inner'>
    <div class='stat-text'>
    0
  </div>
</div>
</div>
C3 Team
</div> -->
<div class='stat <%= trend_stat("Next Steps",:attendance,'month') %>'>
  <div class='circle circle-border'>
    <div class='circle-inner'>
      <div class='stat-text'>
        <%= stat("Next Steps",:attendance,'month') %>
      </div>
    </div>
  </div>
  <div class='caption'>NextSteps</div>
  <div class="previous">
    <%= stat("Next Steps",:attendance,'last month') %>
    <span><%=difference_stat("Next Steps",:attendance,'month')%></span>
  </div>
</div>
<div class='stat <%= trend(giving("month"),giving("last month")) %>'>
  <div class='circle circle-border'>
    <div class='circle-inner'>
      <div class='stat-text giving'>
        $<%= giving('month') %>
      </div>
    </div>
  </div>
  <div class='caption'>Giving</div>
  <div class="previous">
    $<%= giving('last month') %>
    <span><%=difference_giving('month')%></span>
  </div>
</div>
</div>
<div class='half-page four'>
  <div class='title'>
    Yearly Averages
  </div>
  <div class='stat <%= trend_stat("Church",:attendance,'year') %>'>
    <div class='circle circle-border'>
      <div class='circle-inner'>
        <div class='stat-text'>
          <%= stat("Church",:attendance,'year') %>
        </div>
      </div>
    </div>
    <div class='caption'>Attendance</div>
    <div class="previous">
      <%= stat("Church",:attendance,'last year') %>
      <span><%=difference_stat("Church",:attendance,'year')%></span>
    </div>
  </div>
  <div class='stat <%= trend_stat("Church",:visitors,'year') %>'>
    <div class='circle circle-border'>
      <div class='circle-inner'>
        <div class='stat-text'>
          <%= stat("Church",:visitors,'year') %>
        </div>
      </div>
    </div>
    <div class='caption'>Visitors</div>
    <div class="previous">
      <%= stat("Church",:visitors,'last year') %>
      <span><%=difference_stat("Church",:visitors,'year')%></span>
    </div>
  </div>
  <div class='stat <%= trend_stat("Church",:decisions,'year') %>'>
    <div class='circle circle-border'>
      <div class='circle-inner'>
        <div class='stat-text'>
          <%= stat("Church",:decisions,'year') %>
        </div>
      </div>
    </div>
    <div class='caption'>Decisions</div>
    <div class="previous">
      <%= stat("Church",:decisions,'last year') %>
      <span><%=difference_stat("Church",:decisions,'year')%></span>
    </div>
  </div>
  <!--      <div class='stat'>
  <div class='circle circle-border normal'>
  <div class='circle-inner'>
  <div class='stat-text'>
  0
</div>
</div>
</div>
C3 Team
</div> -->
<div class='stat <%= trend_giving("year") %>'>
  <div class='circle circle-border'>
    <div class='circle-inner'>
      <div class='stat-text giving'>
        $<%= giving('year') %>
      </div>
    </div>
  </div>
  <div class='caption'>Giving</div>
  <div class="previous">
    $<%= giving('last year') %>
    <span><%=difference_giving('year')%></span>
  </div>
</div>
</div>
</div>
<footer class='data-date'>
  Data from <strong><%= Meeting.first.created_at.to_formatted_s(:short) %></strong>
</footer>
</section>

app/views/home/admin/_events.html.erb
<% if can?(:manage, Event) %>
<%= content_tag :div, class: 'row dashboard' do %>
<i class='fa fa-3x fa-calendar'></i><span>Events</span>
<ul>
  <li><%= link_to(content_tag(:i," New", class:'fa fa-plus'), new_event_path) %></li>
  <li><%= link_to(content_tag(:i, " List", class: 'fa fa-list'), admin_events_path) %></li>
  <li><%= link_to(content_tag(:i, " Types", class: 'fa fa-folder-open-o'), event_types_path) if can?(:manage, EventType) %></li>
</ul>
<% end end%>

app/views/home/admin/_locations.html.erb
<% if can?(:manage, Location) %>
<%= content_tag :div, class: 'row dashboard' do %>
<i class='fa fa-3x fa-map-marker'></i><span>Locations</span>
<ul>
  <li><%= link_to(content_tag(:i, " New", class: 'fa fa-plus'), new_location_path) %></li>
  <li><%= link_to(content_tag(:i, " List", class: 'fa fa-list'), locations_path) %></li>
</ul>
<% end end %>

app/views/home/admin/_podcasts.html.erb
<%  if can?(:manage, Podcast)%>
<%= content_tag :div, class: 'row dashboard' do %>
<i class='fa fa-3x fa-microphone'></i><span>Podcasts</span>
<ul>
  <li><%= link_to(content_tag(:i, " New", class: 'fa fa-plus'), new_podcast_path) %></li>
  <li><%= link_to(content_tag(:i, " List", class: 'fa fa-list'), podcasts_path) %></li>
</ul>
<% end end %>

app/views/home/admin/_users.html.erb
<%= content_tag :div, class: 'row dashboard' do %>
<i class='fa fa-3x fa-users'></i><span>Users</span>
<ul>
  <li><%= link_to(content_tag(:i, " My Account", class: 'fa fa-cog'), edit_user_registration_path) %></li>
  <li><%= link_to(content_tag(:i, " List", class: 'fa fa-list'), users_path) if can?(:manage, User) %></li>
</ul>
<% end %>