config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "admin/index"

  root to: "home#index"
  get "/.well-known/acme-challenge/:id" => "home#letsencrypt"
  get "/all_locations", to: "locations#all_locations"
  get "/connect_groups/approve", to: "connect_groups#not_approved_index"
  get "/register", to: "connect_groups#new"
  get "/events/revelstoke", to: "events#revelstoke"
  get "/events/kelowna", to: "events#kelowna"
  get "new", to: "home#new"
  resources :connect_groups, :podcasts, :event_types, :events, :messages
  resources :contributions, only: [:new, :create, :index]

  mount Shrine.presign_endpoint(:cache) => "/presign"

  get "app_giving", to: "contributions#new_app"
  get "admin", to: "home#admin"
  get "believe", to: "home#believe"
  get "connect", to: "connect_groups#index"
  get "connection", to: "home#connection"
  get "expect", to: "home#expect"
  get "give", to: "contributions#new"
  get "kids", to: "home#kids"
  get "media", to: "home#media"
  get "nextstep", to: "home#nextstep"
  get "pastors", to: "home#pastors"
  get "vernon", to: "home#vernon"
  get "team", to: "home#pastors"
  get "verse_of_the_day", to: "home#verse_of_the_day"
  get "/team", to: redirect("/pastors")
  get "/vision", to: redirect("believe")
  get "/giving", to: redirect("give")
  get "/feeds/revelstoke", to: "podcasts#revelstoke", defaults: {format: "xml"}
  get "/feeds/kelowna", to: "podcasts#kelowna", defaults: {format: "xml"}
  get "/admin/events", to: "events#admin"

  get "/ajax_load_dashboard", to: "home#ajax_load_dashboard"
  get "/ajax_load_events", to: "home#ajax_load_events"
  get "/ajax_load_locations", to: "home#ajax_load_locations"
  get "/ajax_load_podcasts", to: "home#ajax_load_podcasts"
  get "/ajax_load_connect_groups", to: "home#ajax_load_connect_groups"
  get "/ajax_load_users", to: "home#ajax_load_users"

  #landing page routes go here

  ############################

  match "/loaderio-0077704941f2bf1a629295ce9fb1a229", :to => proc { |env| [200, {}, ["loaderio-0077704941f2bf1a629295ce9fb1a229"]] }, via: :get
  post "podcasts/upload", to: "audio_clips#create"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :locations, only: [:index, :new, :create]
  resources :locations, except: [:index, :new, :create], path: ""

  ### Routing for the new API ###
  namespace :api do
    namespace :v1 do
      resources :locations
      resources :podcasts
      resources :events
      resources :connect_groups
      get "/location/*id", to: "locations#get_location"
      get "/event/featured", to: "events#featured_events"
      get "/homedata", to: "home#index"
    end
  end
end

app/models/home.rb
class Home < ApplicationRecord

	def self.which_sunday(week)
		@week = week - 1
		@today = Date.today
		@current_year = Date.today.year.to_i
		sunday_array(Date.today.month.to_i)
		if Date.new(@current_year, @current_month, @sundays[@week]) <= Time.now.in_time_zone('America/Los_Angeles').to_date
			new_month = Date.today.month.to_i + 1
			new_month == 13 ? new_month = 1 : new_month
			sunday_array(new_month)
		end
		Date.new(@current_year, @current_month, @sundays[@week])
	end
	def self.sunday_array(month)
		@current_month = month
		@days_in_month = Time.days_in_month(@current_month)
		@sundays = Array.new
		@first_sunday = (1..7).find {|d| Date.new(@current_year, @current_month, d).sunday?}
		(@first_sunday...@days_in_month).step(7) {|d| @sundays.push(d).to_ary}
	end
end

app/controllers/api/v1/home_controller.rb
class Api::V1::HomeController < ApiController

  def index
    @featured = Event.all.where(featured: true).order("starttime ASC").as_json(:methods => [:image_url])
    @locations = Location.all.where(show_in_listing: true).as_json(:methods => [:photo_url, :photo_mobile_url, :logo_url])
    render json: { :locations => @locations, :featured => @featured }.to_json
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:admin]
  #  layout :none, only: :verse_of_the_day
  layout "admin", only: :admin
  layout "react", only: :vernon

  def admin
  end

  def index
    @featured = Event.all.where(["starttime > ?", Time.now.ago(2.days)]).order("starttime ASC").where(featured: true).limit(1)
    @listings = Location.all.where(show_in_listing: true)
  end

  def media
    @podcasts = Podcast.all.order("dateof DESC").limit(9)
  end

  def new
    @listings = Location.all.where(show_in_listing: true)
  end

  def expect
    @listings = Location.all.where(show_in_listing: true)
  end

  def nextstep
    @dates = Array.new
    (1..4).each { |d| @dates.push(Home.which_sunday(d)) }
  end

  def vernon
  end

  def letsencrypt
    # use your code here, not mine
    render text: "7fZlPb-fcMhTCqM0v6LKcL5vDJAC79gobZZRZxrSL0c.LUGLpVtUqTXmeOKVq5VWVEEWXPmun8mjkOOfB_gShBE"
  end

  def ajax_load_dashboard
    respond_to do |format|
      format.js
    end
  end

  def ajax_load_events
    respond_to do |format|
      format.js
    end
  end

  def ajax_load_locations
    respond_to do |format|
      format.js
    end
  end

  def ajax_load_podcasts
    respond_to do |format|
      format.js
    end
  end

  def ajax_load_connect_groups
    @connect_groups_not_approved = ConnectGroup.all.where(approved: [nil, false])
    respond_to do |format|
      format.js
    end
  end

  def ajax_load_users
    respond_to do |format|
      format.js
    end
  end
end

app/views/home/admin.html.erb
<% provide(:title, "Admin") %>

<div class="p-admin">


	<section class='o-pageContent p-admin__content'>

		<div class='o-pageContent__section p-admin-content__main container'>
			<% unless current_user.has_role?( :user) %>
			<div class='menu'>
				<%= link_to(content_tag(:i, "", class: 'fa fa-2x fa-calendar'), ajax_load_events_path, title: 'events', remote: true) if can?(:manage, Event)%>
				<%= link_to(content_tag(:i, "", class: 'fa fa-2x fa-map-marker'), ajax_load_locations_path, title: 'locations', remote: true) if can?(:manage, Location)%>
				<%= link_to(content_tag(:i, "", class: 'fa fa-2x fa-microphone'), ajax_load_podcasts_path, title: 'podcasts', remote: true) if can?(:manage, Podcast)%>
				<%= link_to(content_tag(:i, "", class: 'fa fa-2x fa-cogs'), ajax_load_connect_groups_path, title: 'connect groups', remote: true) if can?(:manage, ConnectGroup)%>
				<%= link_to(content_tag(:i, "", class: 'fa fa-2x fa-users'), ajax_load_users_path, title: 'users', remote: true) %>
				<%= link_to(content_tag(:i, "", class: 'fa fa-power-off fa-2x'), destroy_user_session_path, title: 'logout', method: :delete) %>
			</div>
			<div class='admin-panel' id="admin-panel">
				<% if current_user.has_role? :admin %>
				<%= render partial: 'home/admin/events' %>
				<% elsif current_user.has_role? :media%>
				<%= render partial: 'home/admin/podcasts' %>
				<% elsif current_user.has_role?(:pastor) || current_user.has_role?(:creative) %>
				<%= render partial: 'home/admin/events' %>
				<% end %>
			</div>

				<% else %>
			<div class='row'>
				<%= content_tag(:h2, 'You do not have sufficient privileges to access this page') %>
			</div>
				<% end %>
		</div>

	</section>

</div>

app/views/home/ajax_load_connect_groups.js.erb
$("#admin-panel").html('<%= escape_javascript(render partial: "home/admin/connect_groups", locals: {groups: @connect_groups_not_approved}) %>').hide().fadeIn(1200);

app/views/home/ajax_load_locations.js.erb
$("#admin-panel").html('<%= escape_javascript(render partial: "home/admin/locations") %>').hide().fadeIn(1200);

app/views/home/ajax_load_podcasts.js.erb
$("#admin-panel").html('<%= escape_javascript(render partial: "home/admin/podcasts") %>').hide().fadeIn(1200);

app/views/home/ajax_load_users.js.erb
$("#admin-panel").html('<%= escape_javascript(render partial: "home/admin/users") %>').hide().fadeIn(1200);

app/views/home/believe.html.erb
<% provide(:title, "We Believe") %>

<div class="p-believe">
	<header class='o-pageHeader p-believe__header'>
		<div class='o-pageHeader__overlay'></div>
		<h1>What We Believe</h1>
	</header>


	<section class='o-pageContent p-believe__content'>

		<div class='o-pageContent__section p-believe-content container'>
			<h1>C3 Church is You Becoming You!</h1>
			<h2 class='boxed'>We Believe</h2>
			<ul>
			<li>There is one true God: Father, Son, and Holy Spirit.</li>
			<li>Jesus was not only a historical figure, but the Son of God. He lived a life on earth, both human and divine.</li>
			<li>The Holy Spirit comes and empowers our life, giving birth to new character and new gifts. We are all able to experience being fully immersed in the Spirit and receive a powerful prayer language.</li>
			<li>The Bible is given to us by God as His Word. It shows us how to live.</li>
			<li>We live in a world that is not only natural, but spiritual. There are spiritual forces at work both for good and for evil.</li>
			<li>All people are in need of being connected to God. Our faith in Jesus makes this connection possible.</li>
			<li>Water baptism and the Lord&rsquo;s Supper are powerful spiritual experiences that God uses to connect with us and express the fullness of His love towards us.</li>
			<li>We are spiritual beings who will live for eternity. We get a simple, but life-altering choice &mdash; live with God or live alone.</li>
			<li>The church can be a powerful expression of God on the earth. God&rsquo;s desire is that every believer would be active in the local church, fulfilling the Great Commission.</li>
		</ul>
		</div>

	</section>

</div>

app/views/home/expect.html.erb
<% provide(:title, "What To Expect") %>

<div class="p-expect">
	<header class='o-pageHeader p-expect__header'>
		<div class='o-pageHeader__overlay'></div>
		<h1>What To Expect</h1>
	</header>


	<section class='o-pageContent p-expect__content'>


		<div class='o-pageContent__section p-expect-content container'>
			<h2>Anyone and everyone is welcome here...seriously!</h2>
			<p>At C3 Church, you'll find a friendly, casual environment where people are excited to see you. We would like to give you a little idea of what to expect when you arrive at C3 Church, so all you have to do from here is come as you are and find out more for yourself!</p>

			<h3>At a weekend service, you can expect:</h3>
			<ul>
				<li>Each service will last around 70 minutes.
				<ul><li><i class='fa fa-quote-left'></i>We know you are busy and we want you to know we value you and your time.<i class='fa fa-quote-right'></i></li></ul>
				</li>
				<li>High-energy worship music.
				<ul><li><i class='fa fa-quote-left'></i>A music session that will rattle your Grandma’s dentures where we invite everyone to stand and sing with the band (lyrics provided; grandmas allowed)<i class='fa fa-quote-right'></i></li></ul>
				</li>
				<li>Thought-provoking and engaging messages based on the Bible.
				<ul><li><i class='fa fa-quote-left'></i>We are big on practical stuff that we can actually apply to our life this week.<i class='fa fa-quote-right'></i></li></ul>
				</li>
				<li>A place just for kids.
				<ul><li><i class='fa fa-quote-left'></i>Each weekend C3 Kids, ages 4 and up, learn the truth about who God is and who they are because of Him through age-specific lessons and trusted adult leadership. Loaded with interactive activities, it addresses real issues kids face each day.<i class='fa fa-quote-right'></i></li>
				<li><i class='fa fa-quote-left'></i>For ages 3 and under, depending on your location, there is a parents room and/or a supervised nursery. Whichever works best for you.<i class='fa fa-quote-right'></i></li></ul>
				</li>
				<li>GOOD COFFEE!
				<ul><li><i class='fa fa-quote-left'></i>Did we happen to mention that we really like our coffee? You can even bring it into the auditorium.<i class='fa fa-quote-right'></i></li></ul>
				</li>
			</ul>
		</div>

		<div class='o-pageContent__section p-expect-content__locations container'>
			<div class='row'>
					<% @listings.each do |location| %>
					<div class='six columns center'>
					  <h3 class='boxed'><%= location.name %></h3>
					  <p>
						<address><%= location.address %>,<br>
								 <%= location.city%>, <%= location.province %></address>
						<a class='phone' tabIndex="-1" href="tel:<%=location.phone%>"><%= location.phone %></a>
						<br>
						<strong>Sundays</strong> &mdash; <%= location.times %><br>
					  </p>
					</div>
					<% end %>
						</div>
		</div>
	</section>

</div>

app/views/home/index.html.erb
<% provide(:title, "Home") %>
  <% provide(:description, "C3 Church is a charismatic non-denominational church in central British Columbia with locations in Kelowna and Revelstoke. No matter who you are or where you come from, you are welcome here. (Christian City Church)") %>
    <% provide(:navbarClass, "no-background") %>

      <div class="p-home">
        <section class='c-header'>
          <div class='c-header__overlay'></div>
          <div class='c-header__slider'>
            <h1>One Church<br>More Than One Location</h1>
            <a href='#youreInvited'><i class='fa fa-chevron-down'></i></a>
          </div>
        </section>

        <section class='o-pageContent p-home__content'>
          <a name='youreInvited'></a>

          <div class='o-pageContent__section p-home-content__youreInvited'>
            <div class='container'>
              <div class='row'>
                <div class='ten columns offset-by-one'>
                  <h2 class='boxed boxed--white'>You're Invited</h2>
                  <div class='o-serviceList'>
                    <% @listings.each do |location| %>
                      <div class='o-serviceList__service'>
                        <span class='o-serviceList-service__city'><%= location.name %></span>
                        <span class='divider'>/</span>
                        <span class='o-serviceList-service__day'><%= location.day %></span>
                        <span class='divider'>/</span>
                        <span class='o-serviceList-service__timeLocation'><%= location.times %></span>
                      </div>
                      <% end %>

                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class='o-pageContent__section p-home-content__vision'>
            <div class='container'>
              <div class='row'>
                <div class='ten columns offset-by-one'>
                  <h2 class='boxed'>Finding people outside church, bringing them inside and helping them become who they were born to be!</h2>
                </div>
              </div>
            </div>
          </div>

          <div class='o-splitImage o-splitImage--contentInside p-home-content__expect'>
            <div class='o-splitImage__one  p-home-content-expect__img1'>
              <div class='splitImage-image__content'>
                <h2 class='boxed'>What to Expect</h2>
                <p>Whoever you are, you belong here.</p>
                <%= link_to content_tag(:button,'find out more'), expect_path %>
              </div>

              <div class="splitImage-image__overlay"></div>
            </div>

            <div class='o-splitImage__two p-home-content-expect__img2'>
              <div class='splitImage-image__content'>
                <h2 class='boxed'>C3 Kids</h2>
                <p>Kids programs that are safe, clean, and fun to put the parents at ease and moments that are fun and memorable
                  to keep the kids talking.</p>
                <%= link_to content_tag(:button, 'find out more'), kids_path %>
              </div>

              <div class="splitImage-image__overlay"></div>
            </div>
          </div>


          <!-- <div class='o-pageContent p-home-content__nextstep'>
      <%= image_tag 'nextstep.jpg' %>

      <div class='container'>
        <p class='large'>When you walk in the doors of C3 Church, we understand that you might have questions about faith, God, and what we believe. NEXT STEPS is designed to answer some of these questions. You will be equipped and empowered to set a solid foundation for your future at C3, learning about yourself, teams and <%= link_to 'connect groups', connect_groups_path %>.</p>

        <%= link_to content_tag(:button, 'find out more'), nextstep_path  %>
        <br><br><br><br>
      </div>
    </div>
-->
          <div class='o-pageContent__section p-home-content__locations'>
            <div class='container'>
              <div class='row'>
                <div class='ten columns offset-by-one'>
                  <h2 class='boxed boxed--white'>We'd love to meet you.</h2>
                  <br><br><br>
                  <div class='row o-locationList'>
                    <% @listings.each do |location| %>
                      <div class='six columns o-locationList__location o-locationList__location--spacerUnder'>


                        <h3 class='o-locationList-location__name'>
                          <%= image_tag(location.inline_logo.url(:original), class:'location')%>
                        </h3>
                        <span class='o-locationList-location__divider'></span>
                        <address class='o-locationList-location__address'>
                          <%= location.address %>
                        </address>
                        <a class='o-locationList-location_phone' tabIndex="-1" href="tel:<%= location.phone %>">
                          <%= location.phone %>
                        </a>
                        <span class='o-locationList-location__times'><strong><%= location.times %></strong></span>
                        <a href='https://www.google.ca/maps/dir//C3+Church,+<%=location.address%>,+<%=location.city%>,+<%=location.province%>,+<%=location.code%>/@<%=location.latitude%>,<%=location.longitude%>'
                          class='button' target='_blank'>Get Directions</a>

                      </div>
                        <% end %>

                  </div>
                </div>
              </div>
            </div>
          </div>

app/views/home/kids.html.erb
<% provide(:title, "C3 Kids") %>

<div class="p-kids">
	<header class='o-pageHeader p-kids__header'>
		<div class='o-pageHeader__overlay'></div>
		<h1>C3 Kids</h1>
	</header>


	<section class='o-pageContent p-kids__content'>

		<div class='o-pageContent__section p-kids-content__main container'>
			<h2 class='boxed'>Age 4 & up</h2>
			<p>From the moment you check your kids into our C3 Kids area, they will be having fun. The exciting and engaging program and bible curriculum will have them asking to come back.</p>
			<p>All our kids staff are qualified and background checked so you can rest easy.</p>
		</div>

		<div class='o-pageContent__section p-kids-content__nursery container'>
		<h2 class='boxed'>Age 3 & under</h2>
		<h3>We have a couple of options for the youngest kids depending on which location your are attending.</h3>
		<p>There may be a supervised nursery where the kids will have a great time and won't want to go home.</p>
		<p>And/or... if you just need time with your little one to feed or change them, there is a parents room with a live video feed from the main service.<p>
		</div>

	</section>

</div>

app/views/home/media.html.erb
<% provide(:title, "Media") %>

<div class="p-media">
  <header class='o-pageHeader p-media__header'>
    <div class='o-pageHeader__overlay'></div>
    <h1>Media</h1>
  </header>


  <section class='o-pageContent p-media__content'>

    <div class='o-pageContent__section p-media-content container'>
      <div class='0-pageContent__section p-media-content__podcasts container'>
        <h2 class='boxed'>Podcasts</h2>
        <% @podcasts.each_slice(3).each do |row| %>
        <div class='row'>
          <% row.each do |podcast| %>
          <% if podcast %>
          <div class='four columns'>
            <%= content_tag( :h5, podcast.author + " - " + podcast.title, class: 'title') %>
            <div class='meta center'>
              <%= content_tag :span, podcast.dateof.strftime("%B %e, %Y"), class: "date" if podcast.dateof %>
              <%= content_tag :span, podcast.dateof.strftime("%l:%M %P"), class: "time" if podcast.dateof %>
            </div>
            <%= content_tag( :p, podcast.description, class: 'description' ) %>
            <%= content_tag( :div, audio_tag(podcast.podcast_file_path, controls: true), class: 'audio') %>
            <% end %>
            <div class='admin'>
            <% if user_signed_in? && can?(:manage, podcast) %>
              <%= link_to content_tag(:span, 'edit', class: 'edit'), edit_podcast_path(podcast) %>
              <%= link_to content_tag(:span, 'delete', class: 'delete'), podcast, method: :delete, data: { confirm: 'Are you sure?' } %>
              <%= link_to content_tag(:span, 'new', class: 'new'), new_podcast_path %>
              <% end %>
            </div>

          </div>
          <% end %>
        </div>
        <% end %>
      </div>

    </div>
  </section>

</div>

app/views/home/new.html.erb
<% provide(:title, "New?") %>

<div class="p-new">
  <header class='o-pageHeader p-new__header'>
    <div class='o-pageHeader__overlay'></div>
    <h1>New Here</h1>
  </header>


  <section class='o-pageContent p-new__content'>

    <div class='o-pageContent__section p-new-content__visit container'>
      <div class='row'>
        <div class='ten columns offset-by-one'>
          <h2 class='boxed'>Plan A Visit</h2>
          <p>At C3 Church, you'll be welcomed into a friendly, casual environment by people who are excited to see you. In fact we've been thinking about you before you arrive. We want you to have an idea of what to expect when you arrive at C3 Church, so all you have to do from here is come as you are and find out more for yourself!</p>
        </div>
      </div>
    </div>
    <div class='o-pageContent__section p-new-content__pastors container'>
        <div class='row'>
          <div class='ten columns offset-by-one'>
            <h2 class='boxed boxed--white'>Lead Pastors</h2>
          <p>Dave & Kim Olson</p>
          <%= link_to content_tag(:button, 'Meet Them'), pastors_path %>
          <div class='p-new-content_overlay'></div>
          </div>
      </div>
    </div>

    <div class='o-pageContent__section p-new-content__locations container'>
      <div class='row'>
        <% @listings.each do |location| %>
        <div class='six columns center'>
          <h3 class='boxed'><%= location.name %></h3>
          <p>
            <address><%= location.address %>,<br>
                     <%= location.city%>, <%= location.province %></address>
            <a class='phone' tabIndex="-1" href="tel:<%=location.phone%>"><%= location.phone %></a>
            <br>
            <strong>Sundays</strong> &mdash; <%= location.times %><br>
          </p>
        </div>
        <% end %>
      </div>
    </div>


    <div class='o-splitImage o-splitImage--contentInside p-new-content__expect'>
      <div class='o-splitImage__one  p-new-content-expect__img1'>
        <div class='splitImage-image__content'>
          <h2 class='boxed'>What to Expect</h2>
          <p>Whoever you are, you belong here.</p>
          <%= link_to content_tag(:button, 'find out more'), expect_path %>
        </div>

        <div class="splitImage-image__overlay"></div>
      </div>

      <div class='o-splitImage__two p-new-content-expect__img2'>
        <div class='splitImage-image__content'>
          <h2 class='boxed'>What We Believe</h2>
          <p>C3 Church exists for one reason:</br><strong>So You Become You!</strong></p>
          <%= link_to content_tag(:button, 'find out more'), believe_path %>
        </div>

        <div class="splitImage-image__overlay"></div>
      </div>
    </div>
  </section>
</div>

app/views/home/nextstep.html.erb
<% provide(:title, "Next Steps") %>

<div class="p-nextsteps">
	<header class='o-pageHeader p-nextsteps__header'>
	</header>


	<section class='o-pageContent p-nextsteps__content'>
		<div class='o-pageContent__section p-nextsteps-content__nextsteps container'>
			<div class='row'>
				<div class='ten columns offset-by-one'>
							<h2 class='boxed'>Next Steps</h2>
					<p>When you walk in the doors of C3, we understand that you might have questions about faith, God, and what we believe. NEXT STEPS is designed to answer some of these questions. This course is your first step to becoming an integral part of C3 Church. You will be equipped and empowered to set a solid foundation for your future at C3, learning about yourself, teams and <%= link_to("connect groups.", connect_groups_path) %></p>
					<p>Next Steps runs the first four sundays of every month and you can jump in anytime.</p>
				</div>
			</div>
		</div>
		<div class='o-pageContent__section p-nextsteps-content__classes container'>
			<div class='row'>
				<div class=' six columns'>
					<section class='p-nextsteps-content__dna'>
						<h2>DNA 101</h2>
						<p>This class is a basic introduction to C3 Church, our story, statements, strategy and structure. DNA 101 runs on the first sunday of every month and lunch is provided.</p>
						<h3>The next class is <%= @dates[0].to_s(:nextsteps) %></h3>
					</section>
				</div>

				<div class=' six columns'>
					<section class='p-nextsteps-content__essentials'>
						<h2>Essentials 201</h2>
						<p>This class will help guide you through the essential beliefs that every follower of Christ needs to become who they were born to be. Essentials 201 runs on the second sunday of every month</p>
						<h3>The next class is <%= @dates[1].to_s(:nextsteps) %></h3>
					</section>
				</div>
			</div>

			<div class='row'>
				<div class=' six columns'>
					<section class='p-nextsteps-content__discovery'>
						<h2>Discovery 301</h2>
						<p>We want to help you become You. This class will help you discover your personality, gifts, and purpose in life, and see how God combines them for the best fit in ministry. Discovery 301 runs the third sunday of every month</p>
						<h3>The next class is <%= @dates[2].to_s(:nextsteps) %></h3>
					</section>
				</div>

				<div class=' six columns'>
					<section class='p-nextsteps-content__team'>
						<h2>Team 401</h2>
						<p>At Team 401, you will have an opportunity to meet team leaders from different areas, ask your questions and find your place in ministry here at C3 Church. Team 401 runs the fourth sunday of every month</p>
						<h3>The next class is <%= @dates[3].to_s(:nextsteps) %></h3>
					</section>
				</div>
			</div>
			</div>
		<div class='o-pageContent__section p-nextsteps-content__locations container'>

			<h2 class='boxed'>Locations and Times</h2>
				<div class="row">
					<div class="six columns">
						<h2>Kelowna: Sundays @11:30am</h2>
					</div>
					<div class="six columns">
						<h2>Revelstoke: Sundays @11:45am</h2>
					</div>
				</div>

		</section>
</div>

app/views/home/pastors.html.erb
<% provide(:title, "Meet Our Pastors") %>
<% provide(:description, "Dave and Kim Olson are the lead pastors of C3 Church in Kelowna and Revelstoke. C3 Church is a charismatic, non-denominational church in central BC. Everyone is welcome.") %>

<div class="p-pastors">
	<header class='o-pageHeader p-pastors__header'>
		<div class='o-pageHeader__overlay'></div>
		<h1>Lead Pastors</h1>
	</header>


	<section class='o-pageContent p-pastors__content'>

		<div class='o-pageContent__section p-pastors-content container'>
			<h2 class='boxed'>Dave & Kim Olson</h2>
			<h4>Describe yourself in 3 words:</h4>
			<p>Dave: Introspective, Thoughtful, Creative</br>
			Kim: Inclusive, Friendly, Hospitable</p>

			<h4>What is your favourite thing to do in Kelowna/Revelstoke?</h4>
			<p>Dave: C3 Church (Kelowna/Revelstoke)</br>
			Kim: Wine Tours (Kelowna), Having coffee with the locals (Revelstoke)</p>

			<h4>What was your childhood ambition?</h4>
			<p>Dave: Be a pastor</br>
			Kim: Be a lawyer</p>

			<h4>What inspires you?</h4>
			<p>Dave: just about anything creative or unique, business, art and ideas.</br>
			Kim: My children and grandchildren.</p>

			<h4>What do you collect?</h4>
			<p>Dave: Tools</p>
				</div>

	</section>

</div>

app/views/home/vernon.html.erb
<div id="main"></div>
<%= stylesheet_pack_tag 'vernon'%>
<%= javascript_pack_tag 'vernon' %>