config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "admin/index"

  root to: "home#index"
  get "/.well-known/acme-challenge/:id" => "home#letsencrypt"
  get "/all_locations", to: "locations#all_locations"
  get "/connect_groups/approve", to: "connect_groups#not_approved_index"
  get "/register", to: "connect_groups#new"
  get "/events/revelstoke", to: "events#revelstoke"
  get "/events/kelowna", to: "events#kelowna"
  get "new", to: "home#new"
  resources :connect_groups, :podcasts, :event_types, :events, :messages
  resources :contributions, only: [:new, :create, :index]

  mount Shrine.presign_endpoint(:cache) => "/presign"

  get "app_giving", to: "contributions#new_app"
  get "admin", to: "home#admin"
  get "believe", to: "home#believe"
  get "connect", to: "connect_groups#index"
  get "connection", to: "home#connection"
  get "expect", to: "home#expect"
  get "give", to: "contributions#new"
  get "kids", to: "home#kids"
  get "media", to: "home#media"
  get "nextstep", to: "home#nextstep"
  get "pastors", to: "home#pastors"
  get "vernon", to: "home#vernon"
  get "team", to: "home#pastors"
  get "verse_of_the_day", to: "home#verse_of_the_day"
  get "/team", to: redirect("/pastors")
  get "/vision", to: redirect("believe")
  get "/giving", to: redirect("give")
  get "/feeds/revelstoke", to: "podcasts#revelstoke", defaults: {format: "xml"}
  get "/feeds/kelowna", to: "podcasts#kelowna", defaults: {format: "xml"}
  get "/admin/events", to: "events#admin"

  get "/ajax_load_dashboard", to: "home#ajax_load_dashboard"
  get "/ajax_load_events", to: "home#ajax_load_events"
  get "/ajax_load_locations", to: "home#ajax_load_locations"
  get "/ajax_load_podcasts", to: "home#ajax_load_podcasts"
  get "/ajax_load_connect_groups", to: "home#ajax_load_connect_groups"
  get "/ajax_load_users", to: "home#ajax_load_users"

  #landing page routes go here

  ############################

  match "/loaderio-0077704941f2bf1a629295ce9fb1a229", :to => proc { |env| [200, {}, ["loaderio-0077704941f2bf1a629295ce9fb1a229"]] }, via: :get
  post "podcasts/upload", to: "audio_clips#create"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :locations, only: [:index, :new, :create]
  resources :locations, except: [:index, :new, :create], path: ""

  ### Routing for the new API ###
  namespace :api do
    namespace :v1 do
      resources :locations
      resources :podcasts
      resources :events
      resources :connect_groups
      get "/location/*id", to: "locations#get_location"
      get "/event/featured", to: "events#featured_events"
      get "/homedata", to: "home#index"
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
	# rolify

	belongs_to :event_type
	belongs_to :location

	# This method associates the attribute ":avatar" with a file attachment
	has_attached_file :image,
		styles: {
		icon: '40>',
		thumb: '100x100>',
		medium: '300x300>',
		eventThumbnail: '400x225>#',
	},
	convert_options: {
		medium: "-quality 75 -strip",
		eventThumbnail: "-quality 75 -strip"
	},
	default_url: "c3church_event_logo_no_name.png"

	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :title, presence: true
	validates :description, presence: true
	validates :location_id, presence: true
	validates :event_type_id, presence: true
	validates :facebook, presence: false
	validates :facebook,
	format: {:with => URI::regexp(%w(http https)), message: 'Try copying the full address from your browser'},
	allow_blank: true

	def image_url
    	image.url(:eventThumbnail)
    end

end

app/models/event_type.rb
class EventType < ApplicationRecord
	rolify

	has_many :events

	validates :name, presence: true
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApiController
  def index
    @events = Event.all
    render json: @events
  end

  def show
    @events = Event.find(params[:id])
    render json: @events
  end

  def featured_events
      # @featured = Event.all.where(["starttime > ?", Time.now.ago(2.days)]).order("starttime ASC").where(featured: true).limit(1)
      @featured = Event.all.where(featured: true).order("starttime ASC").as_json(:methods => [:image_url])
      render json: @featured
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # Never trust parameters from the scary internet, only allow the white list through.

  def event_params
    params.require(:event).permit(:title, :description, :starttime, :endtime, :image,
                                  :location_id, :featured, :event_type_id, :hash_tag,
                                  :facebook, :repeat, :frequency, :repeat_date, :repeat_day, :repeat_week, :limit)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :revelstoke, :kelowna]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_current_events, only: [:index, :revelstoke, :kelowna]
  load_and_authorize_resource except: [:index, :revelstoke, :kelowna]

  include ActionController::MimeResponds
  require 'icalendar/tzinfo'

  def admin
    @events = Event.all
  end

  def index
    @events = Event.all
  end

  def revelstoke
    calendar = Icalendar::Calendar.new
    tzid = "America/Vancouver"
    tz = TZInfo::Timezone.get tzid
    calendar.add_timezone tz.ical_timezone DateTime.now
    @current_events.each do |item|
      unless item.location.name.downcase == 'kelowna'
        event = Icalendar::Event.new
        calendar.event do |e|
          e.dtstart = Icalendar::Values::DateTime.new item.starttime, 'tzid' => tzid
          e.dtend   = Icalendar::Values::DateTime.new item.endtime, 'tzid' => tzid if item.endtime
          e.summary = item.title
          e.description = item.description
        end
      end
    end
    respond_to do |format|
      format.ics { render text: calendar.to_ical }
    end
  end

  def kelowna
    calendar = Icalendar::Calendar.new
    tzid = "America/Vancouver"
    tz = TZInfo::Timezone.get tzid
    calendar.add_timezone tz.ical_timezone DateTime.now
    @current_events.each do |item|
      unless item.location.name.downcase == 'revelstoke'
        event = Icalendar::Event.new
        calendar.event do |e|
          e.dtstart = Icalendar::Values::DateTime.new item.starttime, 'tzid' => tzid
          e.dtend   = Icalendar::Values::DateTime.new item.endtime, 'tzid' => tzid if item.endtime
          e.summary = item.title
          e.description = item.description
        end
      end
    end
    respond_to do |format|
      format.ics { render text: calendar.to_ical }
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save ? redirect_to(@event, notice: 'Event was successfully created') : render(action: 'new')
  end

  def update
    @event.update(event_params) ? redirect_to(@event, notice: 'Event was successfully updated') : render(action: 'edit')
  end

  def destroy
    @event.destroy
    redirect_to events_url
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def set_current_events
    @current_events = Array.new
    Event.all.each do |event|
      event.limit ||= 0
      if !event.starttime
        event.starttime = DateTime.tomorrow
      end
      if event.starttime.future?
        @current_events.push(event)
      elsif event.repeat      #repeating events
        if event.frequency.downcase == 'daily'
          start = event.starttime
          finish = event.starttime + event.limit.days
          while(start <= finish)
            event.starttime = start
            if event.starttime.future?
              @current_events.push(event)
              start = finish + 1.day
            else start += 1.day
            end
          end
        elsif event.frequency.downcase == 'weekly'
          if event.starttime.wday < event.repeat_day
            diff = event.repeat_day - event.starttime.wday
            event.starttime = event.starttime + diff.days
          else diff = event.starttime.wday - event.repeat_day
            event.starttime = event.starttime - diff.days
          end
          start = event.starttime
          finish = event.starttime + event.limit.weeks
          while(start <= finish)
            event.starttime = start
            if event.starttime.future?
              @current_events.push(event)
              start = finish + 1.week
            else start += 1.week
            end
          end
        elsif event.frequency.downcase == 'monthly'
          beginning_hour = event.starttime.strftime("%H").to_i
          beginning_minute = event.starttime.strftime("%M").to_i
          start = event.starttime
          finish = event.starttime + event.limit.months
          while(start <= finish)
            if event.repeat_date
              event.starttime = start
            else
              current_month = start.month
              current_year = start.year
              working_date = (1..7).find {|d| Date.new(current_year, current_month, d).wday == event.repeat_day}
              event.repeat_week.nil? ? working_date : working_date = working_date + (7*(event.repeat_week-1))
              start = DateTime.new(current_year,current_month,working_date,beginning_hour,beginning_minute)
              event.starttime = start
            end
            if event.starttime.future?
              @current_events.push(event)
              start = finish + 1.month
            else start += 1.month
            end
          end
        end
      end
    end
    @current_events = @current_events.sort_by{|item| [ item['starttime']]}

  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :description, :starttime, :endtime, :image,
    :location_id, :featured, :event_type_id, :hash_tag,
    :facebook, :repeat, :frequency, :repeat_date, :repeat_day, :repeat_week, :limit)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
<%= f.error_notification %>
<div class='row'>
  <div class='four columns'>
    <%= f.input :title, label: false, placeholder: 'Event Title' %>
  </div>
  <div class='four columns'>
    <%= f.input :starttime, as: :datetimepicker, label: false, placeholder: 'Start Time' %>
  </div>
  <div class='four columns'>
    <%= image_tag @event.image.url('thumb'), width: '100' %>
  </div>
</div>
<div class='row'>
  <div class='four columns'>
    <%= f.input :description, label: false, placeholder: 'Description' %>
  </div>
  <div class='four columns'>
    <%= f.input :endtime, as: :datetimepicker, label: false, placeholder: 'End Time' %>
  </div>
  <div class='four columns'>
    <%= f.input :image, label: false %>
  </div>
</div>
<div class='row'>
  <div class='four columns'>
    <%= f.input :hash_tag, label: false, placeholder: '#hashtag' %>
  </div>
  <div class='four columns'>
    <%= f.input :featured, label: 'Featured?', as: :radio_buttons, checked: false %>
  </div>
  <div class='four columns'>
    <%= f.association :location, label: false, as: :radio_buttons %>
  </div>
</div>
<div class='row'>
  <div class='four columns'>
    <%= f.input :facebook, label: false, placeholder: 'Facebook Event URL' %>
  </div>
  <div class='four columns'>
    <%= f.association :event_type, as: :radio_buttons, label: false, checked: 1 %>
  </div>
  <div class='four columns'>
    <%= f.input :repeat, id: 'repeat', label: 'Repeating Event?' %>
  </div>
</div>
<%= content_tag(:div, (f.input :frequency, collection: ['Daily', 'Weekly', 'Monthly'], as: :radio_buttons), class: 'frequency') %>
<%= content_tag(:div, (f.input :repeat_date, label: 'Same Date Every Month?'), class: 'recurring repeat_date') %>
<%= content_tag(:div, (f.input :repeat_day, collection: [['Sunday', 0],  ['Monday', 1], ['Tuesday', 2], ['Wednesday', 3], ['Thursday', 4], ['Friday', 5], ['Saturday', 6]], as: :radio_buttons), class: 'recurring repeat_day') %>
<%= content_tag(:div, (f.input :repeat_week, collection: [['First Week',1], ['Second Week',2], ['Third Week',3], ['Fourth Week',4]], as: :radio_buttons), class: 'recurring repeat_week') %>
<%= content_tag(:div, (f.input :limit, label: 'How many times'), class: 'recurring limit') %>


<%= content_tag :div, class: "form-actions" do %>
<%= f.button :submit, data: {disable_with: "Uploading..."} %>
<% end %>
<% end %>

app/views/events/admin.html.erb
<% provide(:title, "Events") %>

<div class="p-events">


  <section class='o-pageContent p-events__content'>
    <div class='o-pageContent__section p-events-content__events container'>

      <h2 class='boxed'>Events</h2>

      <% @events.each do |event| %>
      <div class='row'>
        <% if event %>
        <%= content_tag :div, image_tag(event.image.url(:thumb), width: '150'), class: "two columns" if event.image %>
        <%= content_tag( :div, event.title, class: 'two columns' ) %>
        <%= content_tag( :div, event.facebook, class: 'two columns' ) %>
        <%= content_tag( :div, event.description, class: 'two columns' ) %>
        <%= content_tag( :div, event.starttime, class: 'one column' ) %>
        <%= event.location.nil? ? content_tag(:div, "Deleted Location", class: 'two columns') : content_tag( :div, event.location.name, class: 'two columns' ) %>
        <%= content_tag :div, class: 'one column admin' do %>
        <%= link_to( content_tag(:i, '', class: 'fa fa-pencil'), edit_event_path(event)) %>
        <%= link_to( content_tag(:i, '',class: 'fa fa-trash'), event, method: :delete, data: { confirm: 'Are you sure?' }) %>
      </div>
      <% end end end %>
      <%= link_to(content_tag(:i, ' Back', class: 'fa fa-hand-o-left'), :back, class: 'button') %>
      <%= link_to(content_tag(:i, 'New Event', class: 'fa fa-plus'), new_event_path, class: 'button') %>
    </div>
  </section>


</div>
</section>
</div>

app/views/events/edit.html.erb
<% provide(:title, "Editing #{@event.title}") %>

<div class="p-events">


  <section class='o-pageContent p-events__content'>
    <div class='o-pageContent__section p-events-content__editing container'>

      <%= render 'form' %>

      <%= link_to(content_tag(:i, ' Show', class: 'fa fa-search'), @event) %> |
      <%= link_to(content_tag(:i, ' Back', class: 'fa fa-hand-o-left'), :back) %>
    </div>
  </div>

app/views/events/index.html.erb
<% provide(:title, "Events") %>

<div class="p-events">
  <header class='o-pageHeader p-events__header'>
    <div class='o-pageHeader__overlay'></div>
    <h1>Events</h1>
  </header>


  <section class='o-pageContent p-events__content'>
    <div class='o-pageContent__section p-events-content__events container'>

      <% @current_events.each_slice(3).each do |group| %>
      <div class='row'>
        <% group.each do |event| %>
        <% if event %>
        <div class='four columns o-event'>
          <%= content_tag :div, image_tag(event.image.url(:eventThumbnail)), class: "o-event__image" if event.image %>
          <div class='o-event__content'>
            <% if event.title %>
            <%= content_tag :h2 do %>
            <%= event.title %>
            <%= content_tag(:span, link_to(content_tag(:i,'',class: 'fa fa-facebook'), event.facebook, target: '_blank'), class: 'facebook') if event.facebook && !event.facebook.blank?  %>
            <% end %>
            <% end %>
            <%= content_tag :p, event.description if event.description %>
            <%= content_tag :span, "in #{event.location.name}", class: "type" if event.location %>
            <div class='meta'>
              <%= content_tag :span, event.starttime.strftime("%B %e, %Y"), class: "date" if event.starttime %>
              <%= content_tag :span, event.starttime.strftime("%l:%M %P"), class: "time" if event.starttime %>
            </div>
            <div class='admin'>
              <% if user_signed_in? && can?( :manage, event) %>
              <%= link_to content_tag(:span, 'edit', class: 'edit'), edit_event_path(event) %>
              <%= link_to content_tag(:span, 'delete', class: 'delete'), event, method: :delete, data: { confirm: 'Are you sure?' } %>
              <%= link_to content_tag(:span, 'new', class: 'new'), new_event_path %>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
  </section>

app/views/events/new.html.erb
<% provide(:title, "New Event") %>

<div class="p-events">


  <section class='o-pageContent p-events__content'>
    <div class='o-pageContent__section p-events-content__editing container'>
      <h2 class='boxed'>New Event</h2>

      <%= render 'form' %>

      <%= link_to(content_tag(:i, ' Back', class: 'fa fa-hand-o-left'), :back) %>
    </div>
  </div>

app/views/events/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<%= image_tag @event.image.url(:medium) %>

<div class: 'white box'>
  <%= @event.description %>
</div>

<p>
  <%= @event.location.name unless @event.location.nil? %>
</p>

  <strong>HashTag:</strong>
  <%= @event.hash_tag if @event.hash_tag %>
</p>
<p>
  <strong>Facebook:</strong>
  <%= @event.facebook if @event.facebook %>
</p>


<p>
  <strong>Starttime:</strong>
  <%= @event.starttime %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @event.endtime %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>