config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "admin/index"

  root to: "home#index"
  get "/.well-known/acme-challenge/:id" => "home#letsencrypt"
  get "/all_locations", to: "locations#all_locations"
  get "/connect_groups/approve", to: "connect_groups#not_approved_index"
  get "/register", to: "connect_groups#new"
  get "/events/revelstoke", to: "events#revelstoke"
  get "/events/kelowna", to: "events#kelowna"
  get "new", to: "home#new"
  resources :connect_groups, :podcasts, :event_types, :events, :messages
  resources :contributions, only: [:new, :create, :index]

  mount Shrine.presign_endpoint(:cache) => "/presign"

  get "app_giving", to: "contributions#new_app"
  get "admin", to: "home#admin"
  get "believe", to: "home#believe"
  get "connect", to: "connect_groups#index"
  get "connection", to: "home#connection"
  get "expect", to: "home#expect"
  get "give", to: "contributions#new"
  get "kids", to: "home#kids"
  get "media", to: "home#media"
  get "nextstep", to: "home#nextstep"
  get "pastors", to: "home#pastors"
  get "vernon", to: "home#vernon"
  get "team", to: "home#pastors"
  get "verse_of_the_day", to: "home#verse_of_the_day"
  get "/team", to: redirect("/pastors")
  get "/vision", to: redirect("believe")
  get "/giving", to: redirect("give")
  get "/feeds/revelstoke", to: "podcasts#revelstoke", defaults: {format: "xml"}
  get "/feeds/kelowna", to: "podcasts#kelowna", defaults: {format: "xml"}
  get "/admin/events", to: "events#admin"

  get "/ajax_load_dashboard", to: "home#ajax_load_dashboard"
  get "/ajax_load_events", to: "home#ajax_load_events"
  get "/ajax_load_locations", to: "home#ajax_load_locations"
  get "/ajax_load_podcasts", to: "home#ajax_load_podcasts"
  get "/ajax_load_connect_groups", to: "home#ajax_load_connect_groups"
  get "/ajax_load_users", to: "home#ajax_load_users"

  #landing page routes go here

  ############################

  match "/loaderio-0077704941f2bf1a629295ce9fb1a229", :to => proc { |env| [200, {}, ["loaderio-0077704941f2bf1a629295ce9fb1a229"]] }, via: :get
  post "podcasts/upload", to: "audio_clips#create"

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :locations, only: [:index, :new, :create]
  resources :locations, except: [:index, :new, :create], path: ""

  ### Routing for the new API ###
  namespace :api do
    namespace :v1 do
      resources :locations
      resources :podcasts
      resources :events
      resources :connect_groups
      get "/location/*id", to: "locations#get_location"
      get "/event/featured", to: "events#featured_events"
      get "/homedata", to: "home#index"
    end
  end
end

app/controllers/event_types_controller.rb
class EventTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event_type, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @event_types = EventType.all
  end

  def new
    @event_type = EventType.new
  end

  def create
    @event_type = EventType.new(event_type_params)
    @event_type.save ? redirect_to(@event_type, notice: 'Event type was successfully created.') : render(action: 'new')
  end

  def update
    @event_type.update(event_type_params) ? redirect_to(@event_type, notice: 'Event type was successfully updated.') : render(action: 'edit')
  end

  def destroy
    @event_type.destroy
    redirect_to event_types_url
  end

  private
# Use callbacks to share common setup or constraints between actions.
def set_event_type
  @event_type = EventType.find(params[:id])
end

# Never trust parameters from the scary internet, only allow the white list through.
def event_type_params
  params.require(:event_type).permit(:name, :description)
end
end

app/helpers/event_types_helper.rb
module EventTypesHelper
end

app/views/event_types/_form.html.erb
<%= simple_form_for(@event_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/event_types/edit.html.erb
<h1>Editing event_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_type %> |
<%= link_to 'Back', event_types_path %>

app/views/event_types/index.html.erb
<h1>Listing event_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @event_types.each do |event_type| %>
    <tr>
      <%= content_tag( :td, link_to(event_type.name, event_type)) %>
      <%= content_tag( :td, event_type.description ) %>
      <%= content_tag( :td, link_to( 'Edit', edit_event_type_path(event_type))) %>
      <%= content_tag( :td, link_to('Destroy', event_type, method: :delete, data: { confirm: 'Are you sure?' })) %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event type', new_event_type_path %>

app/views/event_types/new.html.erb
<h1>New event_type</h1>

<%= render 'form' %>

<%= link_to 'Back', event_types_path %>

app/views/event_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @event_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event_type.description %>
</p>

<%= link_to 'Edit', edit_event_type_path(@event_type) %> |
<%= link_to 'Back', event_types_path %>